"""Definition of ISaveContext."""
from __future__ import annotations

from abc import ABC, abstractmethod
from contextlib import AbstractContextManager
from os import PathLike
from types import TracebackType
from typing import Optional, Type, Union

from overrides import overrides


class ISaveContext(AbstractContextManager, ABC):
    """
    Defines an abstraction for a save medium.

    To separate the concerns of being able to save large associated content in other
    transfer mediums, this interface was defined. It allows out-of-bound data to be
    transferred. Examples include saving to a ZIP file or using an SCP side-channel on
    an SSH connection to send files or other large data objects.
    """

    @overrides
    def __exit__(
        self,
        __exc_type: Type[BaseException] | None,
        __exc_value: BaseException | None,
        __traceback: TracebackType | None,
    ) -> bool | None:
        """Magic method exit."""
        self.close()
        return None

    @abstractmethod
    def save_file(self, source: Union[PathLike, str], content_id: Optional[str]) -> str:
        """
        Save a file to the save medium.

        Note, it is up to the ISaveContext implementation to decide how or when to send the actual
        data. Some ISaveContexts may merely collect metadata as part of this call and actually
        send the data on flush.

        Parameters
        ----------
        source : Union[PathLike, str]
            File on disk to send or include in the save.
        content_id : str, optional
            Unique ID if it already known for this file.
            If an ID is not provided, one is generated and returned.
            This ID can be used with an equivalent ILoadContext to load the contents on deserialize.

        Returns
        -------
        str
            ID, either the one provided or the one otherwise generated.
        """
        ...

    # TODO: What stream API to use?
    # TODO: Async?

    # TODO: Uncomment once we know what stream API to use
    #    @abstractmethod
    #   def save_file_stream(self, source: Union[PathLike, str], id: Optional[str]) \
    #            -> Tuple[Stream, str]:
    #        ...

    @abstractmethod
    def flush(self) -> None:
        """Flush any changes in the context to the underlying stream or file."""
        ...

    @abstractmethod
    def close(self) -> None:
        """Close the context."""
        ...


class ILoadContext(AbstractContextManager, ABC):
    """
    Defines an abstraction for a load medium.

    To separate the concerns of being able to save large associated content in other
    transfer mediums, this interface was defined. It allows out-of-bound data to be
    transferred. Examples include saving to a ZIP file, or using an SCP side-channel on
    an SSH connection to send files or other large data objects.
    """

    @overrides
    def __exit__(
        self,
        __exc_type: Type[BaseException] | None,
        __exc_value: BaseException | None,
        __traceback: TracebackType | None,
    ) -> bool | None:
        self.close()
        return None

    @abstractmethod
    def load_file(self, content_id: Optional[str]) -> Optional[PathLike]:
        """
        Load a file from the load medium.

        The ``ILoadContext`` implementation decides how or when to send the actual
        data. Some ``ILoadContexts`` implementations may merely collect metadata as
        part of this call and actually send the data on flush.

        Parameters
        ----------
        content_id : str, optional
            The id generated by an equivalent ISaveContext to save a file into this context.

        Returns
        -------
        Optional[PathLike]
            Path to the loaded file.
        """
        ...

    # TODO: Uncomment once we know what stream API to use
    #    @abstractmethod
    #    def load_file_stream(self, source: Union[PathLike, str], id: Optional[str]) \
    #            -> Tuple[Stream, str]:
    #        ...

    @abstractmethod
    def flush(self) -> None:
        """Flush any changes in the context to the underlying stream or file."""
        ...

    @abstractmethod
    def close(self) -> None:
        """Close the context."""
        ...
